// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zemacbxlbsydzhmcumbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplbWFjYnhsYnN5ZHpobWN1bWJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MDY2MjQsImV4cCI6MjA3NzQ4MjYyNH0.yZUjOCdjiJCkjIeS5GDeUbTOvV6sotLm1Or5oz6HGdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});